*** Comments ***
Object Repository for Database Access Screen


*** Variables ***
${titleDatabaseAccess}      //h1[contains(.,"Database Access")]
${elemProvAcc}              //td[contains(.,"<<paname>>")]
${elemDBProvider}           //td[contains(.,"<<paname>>")]/parent::tr/td[contains(.,"<<isvname>>")]
${elemInstanceName}         //td[contains(.,"<<inst-name>>")]
${elemInstProvName}         //td[contains(.,"<<inst-name>>")]/parent::tr/td[contains(.,"<<paname>>")]
