*** Comments ***
Object Repository for Import Yaml page


*** Variables ***
${lnkImportYaml}            //a[@aria-label="Import YAML"]
${hdrImportYamlPg}          //h1[.="Import YAML"]
${elemImportTextArea}       //textarea
${btnImportYamlCreate}      //button[@id="save-changes"]
${btnImportYamlCancel}      //button[@id="cancel"]
${btnImportMoreYaml}        //button[.="Import more YAML"]
${txtImportSuccess}         //h2[.="Resources successfully created"]

